fix: compilation errors when building ruby extensions (#98)
Manually specify the language version for C compilation for ruby-build
to avoid error when building ruby and building ruby extensions.

As GCC 15 changes the default language version for C compilation from
`-std=gnu17` to `-std=gnu23`.

This makes the build fail with the following error:

1. `HAVE_STDBOOL_H` not defined, as when checking for stdbool.h, it doesn't
conform to C99 during the ruby building's configure phase.

2. `HAVE_STDBOOL_H` definition required by `ruby/internal/stdbool.h` can
cause potential build fail from corruption in stdbool re-implementation.

Refers: https://gcc.gnu.org/gcc-15/changes.html